'use strict';

const mongoose = require('mongoose');

// All valid token states from spec §5
const TOKEN_STATES = [
  'REQUESTED',
  'RESERVED',
  'CHECKED_IN',
  'WAITING',
  'CALLED',
  'SERVING',
  'COMPLETED',
  'EXPIRED',
  'CANCELLED',
  'NO_SHOW',
];

// Active states: a token is "active" if it hasn't reached a terminal state
const ACTIVE_STATES = ['REQUESTED', 'RESERVED', 'CHECKED_IN', 'WAITING', 'CALLED', 'SERVING'];
const TERMINAL_STATES = ['COMPLETED', 'EXPIRED', 'CANCELLED', 'NO_SHOW'];

const tokenSchema = new mongoose.Schema(
  {
    // ── Identity ─────────────────────────────────────────────────────────
    tokenNumber: {
      type: String,
      required: true,
      // e.g. "OPD042" — generated by token service
    },
    orgId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Organization',
      required: true,
    },
    patientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    serviceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Service',
      required: true,
    },

    // ── Entry method (§3) ─────────────────────────────────────────────────
    source: {
      type: String,
      enum: ['ONLINE', 'WALK_IN'],
      required: true,
    },

    // ── State machine (§5) ────────────────────────────────────────────────
    status: {
      type: String,
      enum: TOKEN_STATES,
      default: 'REQUESTED',
    },

    // ── Date of service ───────────────────────────────────────────────────
    serviceDate: {
      type: String, // 'YYYY-MM-DD' UTC — used for uniqueness index & Redis keys
      required: true,
    },

    // ── Idempotency (§6) ─────────────────────────────────────────────────
    idempotencyKey: {
      type: String,
      required: true,
      // Client-generated UUID per request attempt
    },

    // ── Timestamps (§15) ─────────────────────────────────────────────────
    reservationExpiresAt: {
      type: Date,
      default: null,
    },
    checkedInAt: {
      type: Date,
      default: null,
    },
    calledAt: {
      type: Date,
      default: null,
    },
    servingStartedAt: {
      type: Date,
      default: null,
    },
    completedAt: {
      type: Date,
      default: null,
    },

    // ── Queue position ────────────────────────────────────────────────────
    // Queue ordering is by checkedInAt (§12 fairness policy)
    queuePosition: {
      type: Number,
      default: null,
    },

    // ── Multi-counter (§17) ───────────────────────────────────────────────
    // Assigned at call time, not check-in time
    counterId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Counter',
      default: null,
    },

    // ── No-show rejoin audit trail (§10) ─────────────────────────────────
    // On rejoin, the NEW token links back to the original NO_SHOW token
    noShowTokenRef: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Token',
      default: null,
    },
    // The staff member / receptionist who created walk-in or managed this token
    issuedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
  },
  { timestamps: true }
);

// ── Indexes ────────────────────────────────────────────────────────────────

// One active token per patient+service+date per org (§6 uniqueness constraint)
// Partial index: only enforced for active states (not terminal ones)
tokenSchema.index(
  { patientId: 1, serviceId: 1, serviceDate: 1, orgId: 1 },
  {
    unique: true,
    partialFilterExpression: { status: { $in: ACTIVE_STATES } },
    name: 'unique_active_token_per_patient_service_date',
  }
);

// Idempotency key uniqueness per org (catches duplicate submissions)
tokenSchema.index({ idempotencyKey: 1, orgId: 1 }, { unique: true });

// Queue retrieval: fetch all WAITING tokens for a service sorted by checkedInAt
tokenSchema.index({ orgId: 1, serviceId: 1, serviceDate: 1, status: 1, checkedInAt: 1 });

// Expiry worker: find RESERVED tokens that have passed their expiry time
tokenSchema.index({ status: 1, reservationExpiresAt: 1 });

const Token = mongoose.model('Token', tokenSchema);

module.exports = { Token, TOKEN_STATES, ACTIVE_STATES, TERMINAL_STATES };
